### ISSUE TITLE
One item's title with another's data

### ISSUE THREAD

**Issue by benjaminjkraft** [vsong/markethunt#72]
[Markethunt](https://markethunt.vsong.ca/index.php?item_id=2140) says it's going for, like, 2-3M gold, but actually it looks to be closer to 20k, not sure what's up!

**Comment by vsong** [comment]
The current price displayed is currently 21,141g, not 2M. Can you provide a screenshot?

**Comment by benjaminjkraft** [comment]
Ah, interesting, indeed when I reload it works fine.  I poked a bit more and it seems like some of the time when I type to move through the dropdown I get one item name but another item's data.  Specifically, say I type "cru" to get to "Crucible Cloning Charm", I sometimes get the data for "Creepy Coffin Trap" (the first item matching "cr"), even though the title says "Crucible Cloning Charm".  Maybe a race condition when quickly selecting several items and the data comes back out of order?  Anyway, since a refresh (or selecting more slowly with the mouse) fixes it it's not a big deal so feel free to close if it's too hard to track down.

Screenshot:
![Screenshot 2022-04-30 at 22-31-48 Crucible Cloning Charm - Markethunt](https://user-images.githubusercontent.com/111238/166133611-b1f263c4-920b-4408-8480-f2feff5f757a.png)
